baseURL = "http://example.org/"
languageCode = "ch-zh"
title = "China's risk"
theme = "paper"
disqusShortname = 's'   # add disqus comments

[params]
    # show header social icons
    # twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
    github = 'sequncee'       # github.com/YOUR_GITHUB_ID
    # instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
    rss = true                      # show rss icon with link

    # show home page profile
    avatar = 'GRAVATAR_EMAIL'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
    name = 'Sequnce E'
    bio = 'YOUR_BIO'

    # misc
    disableHLJS = true              # disable requesting highlight.js
    monoDarkIcon = true             # show monochrome dark mode icon